# Generated by Django 3.2.5 on 2021-10-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_quiz_quiz_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='free_book',
            field=models.BooleanField(default=False),
        ),
    ]
