# Generated by Django 3.2.5 on 2021-10-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_book_free_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
