# Generated by Django 3.2.5 on 2021-10-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_book_best_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAudio',
            fields=[
                ('audio_id', models.AutoField(primary_key=True, serialize=False)),
                ('audio', models.FileField(blank=True, default='images/not-available.png', null=True, upload_to='books')),
                ('book', models.ManyToManyField(null=True, to='admin_dashboard.Book')),
            ],
        ),
    ]
