# Generated by Django 3.2.5 on 2021-11-28 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211031_2306'),
        ('admin_dashboard', '0011_cart_cart_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryFeedback',
            fields=[
                ('query_feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('query_feedback_text', models.TextField(max_length=1000)),
                ('query_feedback_subject', models.TextField(max_length=200)),
                ('query_feedback_reply', models.TextField(blank=True, max_length=1000, null=True)),
                ('query_feedback_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
