# Generated by Django 3.2.5 on 2021-10-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_bookaudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='bookaudio',
            name='book',
        ),
        migrations.AddField(
            model_name='bookaudio',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.book'),
        ),
    ]
