# Generated by Django 3.2.5 on 2021-10-30 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_auto_20211029_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmark_audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.bookaudio'),
        ),
    ]
