# Generated by Django 3.2.5 on 2021-10-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_bookmark_bookmark_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark_page_number',
            field=models.IntegerField(null=True),
        ),
    ]
