# Generated by Django 3.2.5 on 2021-10-31 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211031_2306'),
        ('admin_dashboard', '0008_alter_bookmark_bookmark_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
