# Generated by Django 3.2.5 on 2021-11-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_auto_20211031_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicknote',
            name='QuickNote_audio_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.bookaudio'),
        ),
    ]
