# Generated by Django 3.2.5 on 2021-11-11 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_quicknote_quicknote_audio_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
