# Generated by Django 3.2.5 on 2021-11-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0012_queryfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='check_voucher',
            field=models.BooleanField(default=False),
        ),
    ]
